trying to sort out bags

diff --git a/out/baggage b/out/baggage
--- a/out/baggage
+++ b/out/baggage
@@ -1,5 +1,5 @@
 #!/bin/bash
-# Built Fri  8 Nov 2013 23:04:14 GMT
+# Built Sun 10 Nov 2013 07:51:40 GMT
 set -e
 
 export BAGGAGE_APP_BUILT=1
@@ -90,11 +90,205 @@ parse_args()
   app_args $@
 }
 } # app
-bootstrap()
+build()
 {
 
 ################################################################################
-# lib/bootstrap.bash
+# lib/build.bash
+################################################################################
+
+add_header()
+{
+  local header="$1"
+  local out_file="$2"
+
+  echo -e "\n################################################################################" >> "$out_file"
+  echo "# $header" >> "$out_file"
+  echo -e "################################################################################\n" >> "$out_file"
+}
+
+open_method()
+{
+  local name="$1"
+  local out_file="$2"
+
+  echo "${name}()" >> "$out_file"
+  echo "{" >> "$out_file"
+}
+
+close_method()
+{
+  local name="$1"
+  local out_file="$2"
+
+  echo "} # $name" >> "$out_file"
+}
+
+create_file()
+{
+  local out_file="$1"
+  touch "$out_file"
+  chmod +x "$out_file"
+}
+
+add_file()
+{
+  local source_file="$1"
+  local out_file="$2"
+  add_header "$source_file" "$out_file"
+  cat $source_file >> "$out_file"
+}
+
+add_basics()
+{
+  local out_file="$1"
+  cat <<-EOF > "$out_file"
+#!/bin/bash
+# Built $(date)
+set -e
+
+export BAGGAGE_APP_BUILT=1
+export BAGGAGE_APP_NAME="$BAGGAGE_APP_NAME"
+export BAGGAGE_APP_VERSION="$BAGGAGE_APP_VERSION"
+export BAGGAGE_APP_DESCRIPTION="$BAGGAGE_APP_DESCRIPTION"
+
+EOF
+}
+
+add_libs()
+{
+  local out_file="$1"
+
+  [ -d lib ] || return
+
+  for file in lib/*.bash; do
+    name="$(basename ${file%.bash})"
+    open_method "$name" "$out_file"
+    add_file "$file" "$out_file"
+    close_method "$name" "$out_file"
+  done
+}
+
+add_bag()
+{
+  local bag_dir="$1"
+  local out_file="$2"
+
+  bag_name="$(basename $bag_dir)"
+  file="${bag_dir}/out/${bag_name}.bag"
+
+  if [ ! -r "$file" ]; then
+    pushd "$(dirname $bag_dir)" >/dev/null 2>&1
+    $0 install && $0 build
+    popd
+  fi
+  open_method "$bag_name" "$out_file"
+  add_file "$file" "$out_file"
+  close_method "$bag_name" "$out_file"
+}
+
+add_bags()
+{
+  local out_file="$1"
+
+  [ -d bags ] || return
+  for dir in bags/*; do
+    add_bag "$dir" "$out_file"
+  done
+}
+
+add_bins()
+{
+  local out_file="$1"
+
+  [ -d bin ] || return
+  for file in bin/*; do
+    add_file "$file" "$out_file"
+  done
+}
+
+build_app()
+{
+  local out_file="$(pwd)/out/$(app_name)"
+  local dest="$1"
+
+  # Only build an app if we have a bin
+  [ -r "bin/$(app_name)" ] || return
+
+  create_file "$out_file"
+  add_basics "$out_file"
+  #add_bags "$out_file"
+  add_libs "$out_file"
+  add_bins "$out_file"
+
+  if [ -n "$dest" ]; then
+    output=$(cp "$out_file" "$dest" 2>&1)
+    if [ "$?" -ne "0" ]; then
+      if [ "$output" != "${output/Permission denied/}" ]; then
+        # Try sudo
+        sudo cp "$out_file" "$dest"
+      else
+        fatal "Could not install $out_file to $dest"
+      fi
+    fi 
+  fi
+}
+
+build_bag()
+{
+  local out_file="$(pwd)/out/$(app_name).bag"
+  local dest="$1"
+  create_file "$out_file"
+  #add_bags "$out_file"
+  add_libs "$out_file"
+}
+
+build()
+{
+  source "./$BAGGAGE_CONFIG_FILE"
+  local dest="$1"
+  
+  build_app "$dest"
+  build_bag "$dest"
+}
+} # build
+config()
+{
+
+################################################################################
+# lib/config.bash
+################################################################################
+
+name()
+{
+  BAGGAGE_APP_NAME="$1"
+}
+
+version()
+{
+  BAGGAGE_APP_VERSION="$1"
+}
+
+description()
+{
+  BAGGAGE_APP_DESCRIPTION="$1"
+}
+
+ext()
+{
+  return
+}
+
+bag()
+{
+  return
+}
+} # config
+core()
+{
+
+################################################################################
+# lib/core.bash
 ################################################################################
 
 built?()
@@ -140,165 +334,7 @@ load()
     fi
   fi
 }
-
-} # bootstrap
-build()
-{
-
-################################################################################
-# lib/build.bash
-################################################################################
-
-add_header()
-{
-  local header="$1"
-  local app_file="$2"
-
-  echo -e "\n################################################################################" >> "$app_file"
-  echo "# $header" >> "$app_file"
-  echo -e "################################################################################\n" >> "$app_file"
-}
-
-open_method()
-{
-  local name="$1"
-  local app_file="$2"
-
-  echo "${name}()" >> "$app_file"
-  echo "{" >> "$app_file"
-}
-
-close_method()
-{
-  local name="$1"
-  local app_file="$2"
-
-  echo "} # $name" >> "$app_file"
-}
-
-create_file()
-{
-  local app_file="$1"
-  touch "$app_file"
-  chmod +x "$app_file"
-}
-
-add_file()
-{
-  local source_file="$1"
-  local app_file="$2"
-  add_header "$source_file" "$app_file"
-  cat $source_file >> "$app_file"
-}
-
-add_basics()
-{
-  local app_file="$1"
-  cat <<-EOF > "$app_file"
-#!/bin/bash
-# Built $(date)
-set -e
-
-export BAGGAGE_APP_BUILT=1
-export BAGGAGE_APP_NAME="$BAGGAGE_APP_NAME"
-export BAGGAGE_APP_VERSION="$BAGGAGE_APP_VERSION"
-export BAGGAGE_APP_DESCRIPTION="$BAGGAGE_APP_DESCRIPTION"
-
-EOF
-}
-
-add_libs()
-{
-  local app_file="$1"
-
-  [ ! -d lib ] && return
-
-  for file in lib/*.bash; do
-    name="$(basename ${file%.bash})"
-    open_method "$name" "$app_file"
-    add_file "$file" "$app_file"
-    close_method "$name" "$app_file"
-  done
-}
-
-add_bag()
-{
-  local bag_dir="$1"
-  local app_file="$2"
-}
-
-add_bags()
-{
-  local app_file="$1"
-  for dir in bags/*; do
-    add_bag "$dir" "$app_file"
-  done
-}
-
-add_bins()
-{
-  local app_file="$1"
-  for file in bin/*; do
-    add_file "$file" "$app_file"
-  done
-}
-
-build()
-{
-  local app_file="$(pwd)/out/$(app_name)"
-  local dest="$1"
-
-  create_file "$app_file"
-  add_basics "$app_file"
-  add_libs "$app_file"
-  add_bags "$app_file"
-  add_bins "$app_file"
-
-  if [ -n "$dest" ]; then
-    output=$(cp "$app_file" "$dest" 2>&1)
-    if [ "$?" -ne "0" ]; then
-      if [ "$output" != "${output/Permission denied/}" ]; then
-        # Try sudo
-        sudo cp "$app_file" "$dest"
-      else
-        fatal "Could not install $app_file to $dest"
-      fi
-    fi 
-  fi
-}
-} # build
-config()
-{
-
-################################################################################
-# lib/config.bash
-################################################################################
-
-name()
-{
-  BAGGAGE_APP_NAME="$1"
-}
-
-version()
-{
-  BAGGAGE_APP_VERSION="$1"
-}
-
-description()
-{
-  BAGGAGE_APP_DESCRIPTION="$1"
-}
-
-ext()
-{
-  return
-}
-
-bag()
-{
-  return
-}
-} # config
+} # core
 install()
 {
 
@@ -394,11 +430,13 @@ get()
 
 bag()
 {
+  [ -d "bags" ] || mkdir bags
   get "bags" $@
 }
 
 ext()
 {
+  [ -d "ext" ] || mkdir ext
   get "ext" $@
 }
 
@@ -584,16 +622,13 @@ set -e
 
 # Need to bootstrap the bootstrap
 if [ -z "$BAGGAGE_APP_BUILT" ]; then
-  source lib/bootstrap.bash
+  source lib/core.bash
 else
-  bootstrap
+  core
 fi
 
 load app
 load config
 built? || source "./$BAGGAGE_CONFIG_FILE"
 
-if [ "$(app_name)" = "baggage" ]; then
-  # We're being called as a script
-  parse_args $@
-fi
+parse_args $@
