fixed core lib

diff --git a/out/baggage b/out/baggage
--- a/out/baggage
+++ b/out/baggage
@@ -1,5 +1,5 @@
 #!/bin/bash
-# Built Mon 11 Nov 2013 15:28:51 GMT
+# Built Mon 11 Nov 2013 21:04:11 GMT
 set -e
 
 export BAGGAGE_APP_BUILT=1
@@ -14,7 +14,7 @@ export BAGGAGE_APP_DESCRIPTION="Gem-like plugins for bash. Because 'bash' should
 
 # Provides methods that used by projects
 
-except () {
+except() {
   local i=0
   local FRAMES=${#BASH_LINENO[@]}
   # FRAMES-2 skips main, the last one in arrays
@@ -55,24 +55,11 @@ built?()
   fi
 }
 
-info()
-{
-  echo "INFO - $1"
-}
-
-warn()
-{
-  echo "WARN - $1"
-}
-
-error()
-{
-  echo "ERROR - $1"
-}
 
 fatal()
 {
   echo "FATAL - $1"
+  except
   exit 1
 }
 
@@ -89,11 +76,6 @@ load()
     fi
   fi
 }
-
-################################################################################
-# app
-################################################################################
-
 app()
 {
 
@@ -166,6 +148,7 @@ app_args()
       "build")    shift; load build; build $@;;
       "install")  shift; load install; install $@;;
       "run")      shift; load run; run $@;;
+      "thisisdumb") shift; load new; thisisdumb $@;;
     esac
   #done
 }
@@ -176,11 +159,6 @@ parse_args()
   app_args $@
 }
 } # app
-
-################################################################################
-# build
-################################################################################
-
 build()
 {
 
@@ -265,32 +243,17 @@ add_libs()
 
   for file in lib/*.bash; do
     name="$(basename ${file%.bash})"
-    
-    # Skip core as we handle that separately
-    [ "$name" = "core" ] && continue
 
-    add_header "$name" "$out_file"
+    # Skip core as we handle it elsewhere
+    [ "$name" = "core" ] && continue    
+
     open_method "$name" "$out_file"
     add_file "$file" "$out_file"
     close_method "$name" "$out_file"
   done
 }
 
-add_bag_file()
-{
-  local file="$1"
-  local out_file="$2"
-
-  bag_name="$(basename $bag_file)"
-  bag_name="${bag_name%.bag}"
-
-  add_header "$bag_name" "$out_file"
-  open_method "$bag_name" "$out_file"
-  add_file "$file" "$out_file"
-  close_method "$bag_name" "$out_file"
-}
-
-add_bag_dir()
+add_bag()
 {
   local bag_dir="$1"
   local out_file="$2"
@@ -308,25 +271,13 @@ add_bag_dir()
   close_method "$bag_name" "$out_file"
 }
 
-add_bag()
-{
-  local bag="$1"
-  local out_file="$2"
-
-  if [ -f $bag ] && [ "${bag:(-4)}" = ".bag" ]; then
-    add_bag_file "$bag" "$out_file"
-  elif [ -d "$bag" ] && [ -r "${bag}/Baggage" ]; then
-    add_bag_dir "$bag" "$out_file"
-  fi
-}
-
 add_bags()
 {
   local out_file="$1"
 
   [ -d bags ] || return 0
-  for bag in bags/*; do
-    add_bag "$bag" "$out_file"
+  for dir in bags/*; do
+    add_bag "$dir" "$out_file"
   done
 }
 
@@ -353,7 +304,7 @@ build_app()
   create_file "$out_file"
   add_basics "$out_file"
   add_core "$out_file"
-  add_bags "$out_file"
+  #add_bags "$out_file"
   add_libs "$out_file"
   add_bins "$out_file"
 
@@ -378,8 +329,7 @@ build_bag()
 
   echo " Building bag out/$(app_name).bag"
   create_file "$out_file"
-  add_core "$out_file"
-  add_bags "$out_file"
+  #add_bags "$out_file"
   add_libs "$out_file"
 }
 
@@ -392,11 +342,6 @@ build()
   build_bag "$dest"
 }
 } # build
-
-################################################################################
-# config
-################################################################################
-
 config()
 {
 
@@ -429,11 +374,6 @@ bag()
   return
 }
 } # config
-
-################################################################################
-# install
-################################################################################
-
 install()
 {
 
@@ -548,11 +488,6 @@ install()
   source "./$BAGGAGE_CONFIG_FILE"
 }
 } # install
-
-################################################################################
-# new
-################################################################################
-
 new()
 {
 
@@ -623,6 +558,78 @@ create_example_test()
 EOF
 }
 
+create_core_lib()
+{
+  local path="$1"
+  local core_file="${path}/lib/core.bash"
+  cat <<-'EOF' > "$core_file"
+# Provides methods that used by projects
+
+except() {
+  local i=0
+  local FRAMES=${#BASH_LINENO[@]}
+  # FRAMES-2 skips main, the last one in arrays
+  for ((i=FRAMES-2; i>=0; i--)); do
+    echo '  File' \"${BASH_SOURCE[i+1]}\", line ${BASH_LINENO[i]}, in ${FUNCNAME[i+1]}
+    # Grab the source code of the line
+    sed -n -e "${BASH_LINENO[i]}{s/^/    /" -e 'p' -e '}' "${BASH_SOURCE[i+1]}"
+  done
+}
+
+project_name()
+{
+  echo "$BAGGAGE_APP_NAME"
+}
+
+project_path()
+{
+  echo "$BAGGAGE_APP_PATH"
+}
+
+project_version()
+{
+  echo "$BAGGAGE_APP_VERSION"
+}
+
+project_description()
+{
+  echo "$BAGGAGE_APP_DESCRIPTION"
+}
+
+
+built?()
+{
+  if [ -n "$BAGGAGE_APP_BUILT" ]; then
+    return 0
+  else
+    return 1
+  fi
+}
+
+
+fatal()
+{
+  echo "FATAL - $1"
+  except
+  exit 1
+}
+
+load()
+{
+  local name="$1"
+  [ -z "$name" ] && error "load argument missing"
+
+  if built?; then
+    $name
+  else
+    if [ -r "lib/${name}.bash" ]; then
+      source "lib/${name}.bash"
+    fi
+  fi
+}
+EOF
+}
+
 create_example_lib()
 {
   local path="$1"
@@ -646,10 +653,7 @@ create_example_bin()
 #!/bin/bash
 set -e
 
-# TODO - provide basic stuff
-# load example
-source lib/example.bash
-
+load example
 total=0
 while [ \$# -gt 0 ]; do
   total=\$(add_two_numbers "\$total" "\$1")  
@@ -659,6 +663,13 @@ echo "Total: \$total"
 EOF
 
   chmod +x "$bin_file"
+}
+
+thisisdumb()
+{
+  [ -r "$BAGGAGE_CONFIG_FILE" ] || fatal "Must be in baggage root dir"
+  echo "Creating core lib"
+  create_core_lib "./"
 }
 
 new()
@@ -677,15 +688,11 @@ new()
   create_sub_dirs "$new_app_path"
   create_baggage_file "$name" "$new_app_path"
   create_example_test "$new_app_path"
+  create_core_lib "$new_app_path"
   create_example_lib "$new_app_path"
   create_example_bin "$name" "$new_app_path"
 }
 } # new
-
-################################################################################
-# run
-################################################################################
-
 run()
 {
 
@@ -706,11 +713,6 @@ run()
   fi
 }
 } # run
-
-################################################################################
-# test
-################################################################################
-
 test()
 {
 
